# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee1f6fe8009cf0c00c2189b071dbfd6c5fdf74ed65b8f4f1e30e8ff2bdbea445a7b8ad57350d1e7607e286b288a99ccc4bcade621d2eb178285484330baba0d3

test:
  secret_key_base: 4a525e59ec3e12d80a0cbe34d1b535f671103871e339651aa3ed576b0d1bbd40a56d58e36173fa5a9076718e32ce3bf40d022fdcdf6451d392456995280b10a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
